pages = [      # Liste des pages a afficher dans l'ordre / stage est de la forme [jeu, manche]
  { "url": "title.html",              "stage": [1, 0] }, 
  { "url": "Jeu1-choix.html",         "stage": [1, 1] }, 
  { "url": "results.html",            "stage": [1, 1] }, 
  { "url": "Jeu1-choix.html",         "stage": [1, 2] }, 
  { "url": "results.html",            "stage": [1, 2] }, 
  { "url": "Jeu1-choix.html",         "stage": [1, 3] }, 
  { "url": "results.html",            "stage": [1, 3] }, 
  { "url": "title.html",              "stage": [2, 0] }, 
  { "url": "Jeu2-choix.html",         "stage": [2, 1] }, 
  { "url": "Jeu2-reveal.html",        "stage": [2, 1] }, 
  { "url": "results.html",            "stage": [2, 1] }, 
  { "url": "Jeu2-choix.html",         "stage": [2, 2] }, 
  { "url": "Jeu2-reveal.html",        "stage": [2, 2] }, 
  { "url": "results.html",            "stage": [2, 2] }, 
  { "url": "Jeu2-choix.html",         "stage": [2, 3] }, 
  { "url": "Jeu2-reveal.html",        "stage": [2, 3] }, 
  { "url": "results.html",            "stage": [2, 3] }, 
  { "url": "title.html",              "stage": [3, 0] }, 
  { "url": "Jeu3-choix.html",         "stage": [3, 1] }, 
  { "url": "results.html",            "stage": [3, 1] }, 
  { "url": "Jeu3-choix.html",         "stage": [3, 2] }, 
  { "url": "results.html",            "stage": [3, 2] }, 
  { "url": "Jeu3-choix.html",         "stage": [3, 3] }, 
  { "url": "results.html",            "stage": [3, 3] }, 
  { "url": "title.html",              "stage": [4, 0] }, 
  { "url": "Jeu4-choix.html",         "stage": [4, 1] }, 
  { "url": "Jeu4-reveal.html",        "stage": [4, 1] }, 
  { "url": "results.html",            "stage": [4, 1] }, 
  { "url": "Jeu4-choix.html",         "stage": [4, 2] }, 
  { "url": "Jeu4-reveal.html",        "stage": [4, 2] }, 
  { "url": "results.html",            "stage": [4, 2] }, 
  { "url": "Jeu4-choix.html",         "stage": [4, 3] }, 
  { "url": "Jeu4-reveal.html",        "stage": [4, 3] }, 
  { "url": "results.html",            "stage": [4, 3] }, 
  { "url": "donner_des_etoiles.html", "stage": [4, None] }, 
  { "url": "results.html",            "stage": [4, None] }, 
  { "url": "title.html",              "stage": [5, 0] }, 
  { "url": "Jeu 5",                   "stage": [5, 1], "phase": "proposition" }, 
  { "url": "Jeu 5",                   "stage": [5, 1], "phase": "validation" }, 
  { "url": "Jeu 5",                   "stage": [5, 1], "phase": "reveal" }, 
  { "url": "Jeu 5",                   "stage": [5, 2], "phase": "proposition" }, 
  { "url": "Jeu 5",                   "stage": [5, 2], "phase": "validation" }, 
  { "url": "Jeu 5",                   "stage": [5, 2], "phase": "reveal" }, 
  { "url": "Jeu 5",                   "stage": [5, 3], "phase": "proposition" }, 
  { "url": "Jeu 5",                   "stage": [5, 3], "phase": "validation" }, 
  { "url": "Jeu 5",                   "stage": [5, 3], "phase": "reveal" }, 
  { "url": "final-results.html",      "stage": [5, None] }
]

