# Liste des pages a afficher dans l'ordre, stage est de la forme (jeu, manche)
pages = [
  { "url": "choIx_couleurs.jinja", "stage": (1, None), "heading":None}, 
  { "url": "title.jinja",          "stage": (1, 0), "heading":"dons"}, 
  { "url": "Jeu1-choix.jinja",     "stage": (1, 1), "heading":"dons" }, 
  { "url": "results.jinja",        "stage": (1, 1), "heading":"dons" }, 
  { "url": "Jeu1-choix.jinja",     "stage": (1, 2), "heading":"dons" }, 
  { "url": "results.jinja",        "stage": (1, 2), "heading":"dons" }, 
  { "url": "Jeu1-choix.jinja",     "stage": (1, 3), "heading":"dons" }, 
  { "url": "results.jinja",        "stage": (1, 3), "heading":"dons" }, 
  { "url": "title.jinja",          "stage": (2, 0), "heading":"dons" }, 
  { "url": "Jeu2-choix.jinja",     "stage": (2, 1), "heading":"dons" }, 
  { "url": "Jeu2-reveal.jinja",    "stage": (2, 1), "heading":"dons" }, 
  { "url": "results.jinja",        "stage": (2, 1), "heading":"dons" }, 
  { "url": "Jeu2-choix.jinja",     "stage": (2, 2), "heading":"dons" }, 
  { "url": "Jeu2-reveal.jinja",    "stage": (2, 2), "heading":"dons" }, 
  { "url": "results.jinja",        "stage": (2, 2), "heading":"dons" }, 
  { "url": "Jeu2-choix.jinja",     "stage": (2, 3), "heading":"dons" }, 
  { "url": "Jeu2-reveal.jinja",    "stage": (2, 3), "heading":"dons" }, 
  { "url": "results.jinja",        "stage": (2, 3), "heading":"dons" }, 
  { "url": "title.jinja",          "stage": (3, 0), "heading":"dons" }, 
  { "url": "Jeu3-choix.jinja",     "stage": (3, 1), "heading":"dons" }, 
  { "url": "results.jinja",        "stage": (3, 1), "heading":"dons" }, 
  { "url": "Jeu3-choix.jinja",     "stage": (3, 2), "heading":"dons" }, 
  { "url": "results.jinja",        "stage": (3, 2), "heading":"dons" }, 
  { "url": "Jeu3-choix.jinja",     "stage": (3, 3), "heading":"dons" }, 
  { "url": "results.jinja",        "stage": (3, 3), "heading":"dons" }, 
  { "url": "title.jinja",          "stage": (4, 0), "heading":"dons" }, 
  { "url": "Jeu4-choix.jinja",     "stage": (4, 1), "heading":"dons" }, 
  { "url": "Jeu4-reveal.jinja",    "stage": (4, 1), "heading":"dons" }, 
  { "url": "results.jinja",        "stage": (4, 1), "heading":"dons" }, 
  { "url": "Jeu4-choix.jinja",     "stage": (4, 2), "heading":"dons" }, 
  { "url": "Jeu4-reveal.jinja",    "stage": (4, 2), "heading":"dons" }, 
  { "url": "results.jinja",        "stage": (4, 2), "heading":"dons" }, 
  { "url": "Jeu4-choix.jinja",     "stage": (4, 3), "heading":"dons" }, 
  { "url": "Jeu4-reveal.jinja",    "stage": (4, 3), "heading":"dons" }, 
  { "url": "results.jinja",        "stage": (4, 3), "heading":"dons" }, 
  { "url": "choix_etoiles.jinja",  "stage": (5, None), "heading":"dons" }, 
  { "url": "results.jinja",        "stage": (5, None), "heading":"etoiles" }, 
  { "url": "title.jinja",          "stage": (5, 0), "heading":None }, 
  { "url": "Jeu 5",                "stage": (5, 1), "heading":None, "phase": "proposition" }, 
  { "url": "Jeu 5",                "stage": (5, 1), "heading":None, "phase": "validation" }, 
  { "url": "Jeu 5",                "stage": (5, 1), "heading":None, "phase": "reveal" }, 
  { "url": "Jeu 5",                "stage": (5, 2), "heading":None, "phase": "proposition" }, 
  { "url": "Jeu 5",                "stage": (5, 2), "heading":None, "phase": "validation" }, 
  { "url": "Jeu 5",                "stage": (5, 2), "heading":None, "phase": "reveal" }, 
  { "url": "Jeu 5",                "stage": (5, 3), "heading":None, "phase": "proposition" }, 
  { "url": "Jeu 5",                "stage": (5, 3), "heading":None, "phase": "validation" }, 
  { "url": "Jeu 5",                "stage": (5, 3), "heading":None, "phase": "reveal" }, 
  { "url": "final-results.jinja",  "stage": (5, None), "heading":None }
]
